name: Build Financial Calendar

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

permissions:
  contents: write

jobs:
  build-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Build calendar file
        run: python financial_calendar_ical_feed.py --build

      - name: Commit updated calendar
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update macro calendar
          file_pattern: macro-calendar.ics
